server:
  port: 8089

tencentcloudapi:
  # 你的 secretId
  secretId: asdasda
  # 你的 secretKey
  secretKey: asdasd
  # 请求官方地址 不变
  endpoint: iai.tencentcloudapi.com
  #地域 可不变
  region: ap-shanghai

spring:
  datasource:
    url: jdbc:mysql://******/face_uidb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: ****
    password: ****
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  typeAliasesPackage: com.face.bean
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
